### ISSUE TITLE
Not finding Watchlist in tv.py

### ISSUE THREAD

**Issue by johnmolino** [timelyart/Kairos#120]
Hello - trying 3.18 and still not able to get a full browse of the Watchlist..  It clicks the Watchlist dropdown and then nothing. It leaves the menu open....then the program will exit. It's like it cannot click the watchlist dropdown menu successfully.  I also put a breakpoint the tv.py at line 1202 and used the python debugger to check all the parameters for options_watchlist (they are correct).   It's failing on find_elements().

Windows 10, Brave is up to date
[Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)](https://brave.com/latest/) - I tried both 32bit and 64bit versions of Chromedriver.  

Is this a bug, or my computer?  I guess I could install on an extra laptop and give it a whirl if nothing else.....

Thank you.    

- here's the command output:
c:\Kairos-3.18>python main.py browse.yaml

========================================
2024-09-11 18:50:40 - Start Program
========================================

DISCLAIMER
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

USAGE
python main.py [<file>] [-s|-s <minutes>] [-h] [-d]
For help, type: python main.py -h

2024-09-11 18:50:40.223 INFO tv - run: Running on a windows operating system
2024-09-11 18:50:41.772 INFO tv - assign_user_data_directory: kairos_0 assigned
2024-09-11 18:50:41.910 INFO utils - download_chromedriver: Chromedriver is already installed.
2024-09-11 18:50:41.911 INFO tv - create_browser: using c:\128\chromedriver.exe as webdriver

DevTools listening on ws://127.0.0.1:55243/devtools/browser/30e0ba9b-99e3-4842-a8c7-b38fcfb1233f
2024-09-11 18:50:42.896 INFO tv - check_driver: browser version: 128.0.6613.138
2024-09-11 18:50:42.896 INFO tv - check_driver: driver version: 128.0.6613.137
2024-09-11 18:50:47.922 INFO tv - login: already logged in (Premium account)
2024-09-11 18:50:52.181 INFO tv - open_chart: opening chart https://www.tradingview.com/chart/SGwRjWll/
2024-09-11 18:50:52.182 INFO tv - open_chart: WAIT_TIME_IMPLICIT = 0.0
2024-09-11 18:50:52.183 INFO tv - open_chart: PAGE_LOAD_TIMEOUT = 60.0
2024-09-11 18:50:52.184 INFO tv - open_chart: CHECK_IF_EXISTS_TIMEOUT = 10.0
2024-09-11 18:50:52.185 INFO tv - open_chart: DELAY_BREAK_MINI = 0.1
2024-09-11 18:50:52.186 INFO tv - open_chart: DELAY_BREAK = 0.25
2024-09-11 18:50:52.186 INFO tv - open_chart: DELAY_SUBMIT_ALERT = 0.0
2024-09-11 18:50:52.187 INFO tv - open_chart: DELAY_CHANGE_SYMBOL = 5
2024-09-11 18:50:52.187 INFO tv - open_chart: DELAY_CLEAR_INACTIVE_ALERTS = 2.0
2024-09-11 18:50:52.188 INFO tv - open_chart: DELAY_KEYSTROKE = 0.01
2024-09-11 18:50:52.188 INFO tv - open_chart: DELAY_READ_INDICATOR_VALUE = 0.2
2024-09-11 18:50:52.188 INFO tv - open_chart: READ_FROM_DATA_WINDOW = True
2024-09-11 18:50:52.189 INFO tv - open_chart: WAIT_UNTIL_CHART_IS_LOADED = False
2024-09-11 18:50:52.190 INFO tv - open_chart: READ_ALL_VALUES_AT_ONCE = True
2024-09-11 18:50:52.190 INFO tv - open_chart: CHANGE_SYMBOL_WITH_SPACE = False
2024-09-11 18:50:52.192 INFO tv - open_chart: VERIFY_MARKET_LISTING = False
2024-09-11 18:50:52.193 INFO tv - open_chart: ACCEPT_PERFORMANCE_ANALYTICS_COOKIES = False
2024-09-11 18:50:52.195 INFO tv - open_chart: ACCEPT_ADVERTISING_COOKIES = False

2024-09-11 18:51:04.674 ERROR tv - open_chart: Message:

Traceback (most recent call last):
  File "c:\Kairos-3.18\tv\tv.py", line 1203, in open_chart
    el_options = find_elements(browser, css_selectors['options_watchlist'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Kairos-3.18\tv\tv.py", line 512, in find_elements
    elements = WebDriverWait(browser, delay).until(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jm\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium-4.24.0-py3.12.egg\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

2024-09-11 18:51:04.973 ERROR tv - snapshot: log\20240911_185104.png
2024-09-11 18:51:04.974 INFO tv - run: No alerts or signals set

2024-09-11 18:51:04.975 INFO tv - run: No signals triggered. Nothing to send

========================================
2024-09-11 18:51:11 - End Program
Elapsed time: 31 seconds
========================================

**Comment by timelyart** [comment]
I did not have a whole lot of time to test today but it should be fixed in [v3.19](https://github.com/timelyart/Kairos/releases/tag/v3.19). If not, please re-open this issue.

**Comment by johnmolino** [comment]
3.19 fixed browse.yaml!  Thank you! 

screener_to_watchlist.yaml still not working.  Probably the same css.  error below:

Question: how come I'm the only one experiencing this and reporting this?  Do you still use this daily?  Thanks - John

c:\Kairos-3.19>python main.py screener_to_watchlist.yaml

========================================
2024-09-12 18:38:45 - Start Program
========================================

DISCLAIMER
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.


USAGE
python main.py [<file>] [-s|-s <minutes>] [-h] [-d]
For help, type: python main.py -h

2024-09-12 18:38:46.193 INFO tv - run: Running on a windows operating system
2024-09-12 18:38:48.667 INFO tv - assign_user_data_directory: kairos_0 assigned
2024-09-12 18:38:48.668 INFO tv - create_browser: using c:\chromedriver.exe as webdriver

DevTools listening on ws://127.0.0.1:64003/devtools/browser/be90711b-9acc-4abd-9fc4-341b8c8cd84d
2024-09-12 18:38:49.718 INFO tv - check_driver: browser version: 128.0.6613.138
2024-09-12 18:38:49.719 INFO tv - check_driver: driver version: 128.0.6613.137
2024-09-12 18:38:52.720 INFO tv - login: already logged in (Premium account)
2024-09-12 18:38:52.721 INFO tv - run: WAIT_TIME_IMPLICIT = 0.0
2024-09-12 18:38:52.721 INFO tv - run: PAGE_LOAD_TIMEOUT = 60.0
2024-09-12 18:38:52.721 INFO tv - run: CHECK_IF_EXISTS_TIMEOUT = 10.0
2024-09-12 18:38:52.721 INFO tv - run: DELAY_BREAK_MINI = 0.1
2024-09-12 18:38:52.721 INFO tv - run: DELAY_BREAK = 0.25
2024-09-12 18:38:52.722 INFO tv - run: DELAY_SUBMIT_ALERT = 0.0
2024-09-12 18:38:52.722 INFO tv - run: DELAY_CHANGE_SYMBOL = 1.0
2024-09-12 18:38:52.722 INFO tv - run: DELAY_CLEAR_INACTIVE_ALERTS = 2.0
2024-09-12 18:38:52.722 INFO tv - run: DELAY_KEYSTROKE = 0.05
2024-09-12 18:38:52.722 INFO tv - run: DELAY_READ_INDICATOR_VALUE = 0.2
2024-09-12 18:38:52.722 INFO tv - run: READ_FROM_DATA_WINDOW = True
2024-09-12 18:38:52.723 INFO tv - run: WAIT_UNTIL_CHART_IS_LOADED = True
2024-09-12 18:38:52.723 INFO tv - run: READ_ALL_VALUES_AT_ONCE = True
2024-09-12 18:38:52.723 INFO tv - run: CHANGE_SYMBOL_WITH_SPACE = False
2024-09-12 18:38:52.723 INFO tv - run: VERIFY_MARKET_LISTING = False

2024-09-12 18:38:52.723 INFO tv - run: create/update watchlist 'Kairos' from screener. Please be patient, this may take several minutes ...
2024-09-12 18:39:26.341 ERROR tv - run: Message:
Stacktrace:
        GetHandleVerifier [0x00AFD933+25811]
        (No symbol) [0x00A8E314]
        (No symbol) [0x00982523]
        (No symbol) [0x009C7483]
        (No symbol) [0x009C765B]
        (No symbol) [0x00A06BA2]
        (No symbol) [0x009EAD74]
        (No symbol) [0x00A046F0]
        (No symbol) [0x009EAAC6]
        (No symbol) [0x009BBEFD]
        (No symbol) [0x009BC8FD]
        GetHandleVerifier [0x00DCF143+2981091]
        GetHandleVerifier [0x00E22FF9+3324825]
        GetHandleVerifier [0x00B8B32F+605903]
        GetHandleVerifier [0x00B92CBC+637020]
        (No symbol) [0x00A96F4D]
        (No symbol) [0x00A93DD8]
        (No symbol) [0x00A93F75]
        (No symbol) [0x00A86406]
        BaseThreadInitThunk [0x7762FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77C180CE+286]
        RtlGetAppContainerNamedObjectPath [0x77C1809E+238]

Traceback (most recent call last):
  File "c:\Kairos-3.19\tv\tv.py", line 3449, in run
    markets = get_screener_markets(browser, screener_yaml)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Kairos-3.19\tv\tv.py", line 3549, in get_screener_markets
    wait_and_click(browser, css_selectors['select_screener'], delay=30)
  File "c:\Kairos-3.19\tv\tv.py", line 446, in wait_and_click
    return WebDriverWait(browser, delay).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jm\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium-4.24.0-py3.12.egg\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
        GetHandleVerifier [0x00AFD933+25811]
        (No symbol) [0x00A8E314]
        (No symbol) [0x00982523]
        (No symbol) [0x009C7483]
        (No symbol) [0x009C765B]
        (No symbol) [0x00A06BA2]
        (No symbol) [0x009EAD74]
        (No symbol) [0x00A046F0]
        (No symbol) [0x009EAAC6]
        (No symbol) [0x009BBEFD]
        (No symbol) [0x009BC8FD]
        GetHandleVerifier [0x00DCF143+2981091]
        GetHandleVerifier [0x00E22FF9+3324825]
        GetHandleVerifier [0x00B8B32F+605903]
        GetHandleVerifier [0x00B92CBC+637020]
        (No symbol) [0x00A96F4D]
        (No symbol) [0x00A93DD8]
        (No symbol) [0x00A93F75]
        (No symbol) [0x00A86406]
        BaseThreadInitThunk [0x7762FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77C180CE+286]
        RtlGetAppContainerNamedObjectPath [0x77C1809E+238]

2024-09-12 18:39:26.619 ERROR tv - snapshot: log\20240912_183926.png

========================================
2024-09-12 18:39:28 - End Program
Elapsed time: 42 seconds
========================================

**Comment by timelyart** [comment]
Seems I introduced a boo boo with the previous patch. What can I say, mea culpa, I had a bad day. (8
Please, update to [v3.20](https://github.com/timelyart/Kairos/releases/tag/v3.20). 

As to your question, I don't think many people use Kairos. Either people are successful and move on from Kairos and use a paid service, or they lose their money together with their interest.
