### ISSUE TITLE
Signals not working

### ISSUE THREAD

**Issue by debonair99** [timelyart/Kairos#37]
2021-11-13 11:29:41.112 INFO tv - check_driver: browser version: 95.0.4638.69
2021-11-13 11:29:41.113 INFO tv - check_driver: driver version: 95.0.4638.69
2021-11-13 11:29:43.862 INFO tv - login: already logged in
2021-11-13 11:29:47.334 INFO tv - open_chart: opening chart https://www.tradingview.com/chart/nfxFh2Vb/
2021-11-13 11:29:47.334 INFO tv - open_chart: WAIT_TIME_IMPLICIT = 0.0
2021-11-13 11:29:47.337 INFO tv - open_chart: PAGE_LOAD_TIMEOUT = 60.0
2021-11-13 11:29:47.338 INFO tv - open_chart: CHECK_IF_EXISTS_TIMEOUT = 10.0
2021-11-13 11:29:47.338 INFO tv - open_chart: DELAY_BREAK_MINI = 0.1
2021-11-13 11:29:47.339 INFO tv - open_chart: DELAY_BREAK = 0.25
2021-11-13 11:29:47.339 INFO tv - open_chart: DELAY_SUBMIT_ALERT = 0.9
2021-11-13 11:29:47.340 INFO tv - open_chart: DELAY_CHANGE_SYMBOL = 0.15
2021-11-13 11:29:47.340 INFO tv - open_chart: DELAY_CLEAR_INACTIVE_ALERTS = 2.0
2021-11-13 11:29:47.344 INFO tv - open_chart: DELAY_KEYSTROKE = 0.01
2021-11-13 11:29:47.346 INFO tv - open_chart: DELAY_READ_INDICATOR_VALUE = 0.2
2021-11-13 11:29:47.348 INFO tv - open_chart: READ_FROM_DATA_WINDOW = True
2021-11-13 11:29:47.348 INFO tv - open_chart: WAIT_UNTIL_CHART_IS_LOADED = True
2021-11-13 11:29:47.349 INFO tv - open_chart: READ_ALL_VALUES_AT_ONCE = True
2021-11-13 11:29:47.350 INFO tv - open_chart: CHANGE_SYMBOL_WITH_SPACE = False
2021-11-13 11:29:47.350 INFO tv - open_chart: VERIFY_MARKET_LISTING = True
2021-11-13 11:29:52.578 ERROR tv - open_chart: Message: element click intercepted: Element <div class="button-1SoiPS-f button-pg6Iiu-y apply-common-tooltip isOpened-1SoiPS-f isOpened-pg6Iiu-y" data-role="button" data-name="watchlists-button">...</div> is not clickable at point (1525, 24). Other element would receive the click: <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28">...</svg>
  (Session info: chrome=95.0.4638.69)
Traceback (most recent call last):
  File "C:\Kairos-2.59\tv\tv.py", line 1104, in open_chart
    wait_and_click(browser, css_selectors['btn_watchlist_menu_menu'])
  File "C:\Kairos-2.59\tv\tv.py", line 406, in wait_and_click
    ec.element_to_be_clickable((locator_strategy, locator))).click()
  File "C:\Users\61412\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\61412\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\61412\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\61412\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="button-1SoiPS-f button-pg6Iiu-y apply-common-tooltip isOpened-1SoiPS-f isOpened-pg6Iiu-y" data-role="button" data-name="watchlists-button">...</div> is not clickable at point (1525, 24). Other element would receive the click: <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28">...</svg>
  (Session info: chrome=95.0.4638.69)

2021-11-13 11:29:52.929 ERROR tv - snapshot: log\20211113_112952.png
2021-11-13 11:29:52.930 INFO tv - run: No alerts or signals set
2021-11-13 11:29:52.933 INFO tv - run: No signals triggered. Nothing to send
![20211113_112952](https://user-images.githubusercontent.com/85971842/141598385-669f7745-78fe-40fd-8790-a7203f9bb372.png)

**Comment by timelyart** [comment]
Are you running Kairos in 'background' mode?

**Comment by debonair99** [comment]
Yes. I have tried it both ways. I will try the new version v2.60 and see
what happens

**Comment by debonair99** [comment]
> Yes. I have tried it both ways. I will try the new version v2.60 and see what happens

Tried to run again. Same result
[error.txt](https://github.com/timelyart/Kairos/files/7531783/error.txt)

**Comment by debonair99** [comment]
I figured out what happened. Ignore, can close the case. Cheers
