### ISSUE TITLE
set_indicator_dialog_value error 

### ISSUE THREAD

**Issue by marcfon** [timelyart/Kairos#39]
Different error related to `set_indicator_dialog_value`.

```
2021-11-13 15:21:39.701 ERROR tv - set_indicator_dialog_value: Message: 
Traceback (most recent call last):
  File "/kairos/tv/tv.py", line 4282, in set_indicator_dialog_value
    element = find_element(browser, css)
  File "/kairos/tv/tv.py", line 444, in find_element
    element = WebDriverWait(browser, delay).until(
  File "/usr/local/lib/python3.8/site-packages/selenium-3.141.0-py3.8.egg/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Comment by timelyart** [comment]
That is not a whole lot of information to go by. I added some extra information (including a screenshot) when a value cannot be set on the strategy settings dialog. Please, run again with the [latest release](https://github.com/timelyart/Kairos/releases/tag/v2.62) and post the resulting log and screenshot.

**Comment by marcfon** [comment]
Sure, I'm happy to provide any info you need. It seems to fail the moment it has found the specific field.

As a test I'm trying to change the input field name ([screenshot](https://imgur.com/a/coP7cCS))

This is the config in my `strategies.yaml`.

`inputs: {_name: 'Kairos'}`

Tested with v2.62.

**Comment by timelyart** [comment]
Look like Kairos cannot find the `input` or `property` named `_name`. 

Use something like this:
`inputs: {name: "QLS", bot_type: "Single-point", exchange_buy_fee: 0.25, sell_fee: 0.25}`

I see you have icons in front of the input names. This is new to me. That maybe why Kairos cannot find your inputs as Kairos checks whether an input starts with defined YAML values.

Note that Kairos saves a screenshot under `<installation path>\Kairos\log folder` on many occasions when an error occurs.

**Comment by marcfon** [comment]
It looks to me as the emojis are just ignored as they are non-latin non-number characters. From what I can observe `_name` is found while `name` isn't. The `_` makes sense as there is a space between the emoji and the label.

On closer inspection it also seems that `set_indicator_dialog_value` did find `_name` but fails to set the value (see below).

```
2021-11-13 20:45:54.264 ERROR tv - set_indicator_dialog_value: unable to set _name to Kairos
Traceback (most recent call last):
  File "/kairos/tv/tv.py", line 4282, in set_indicator_dialog_value
    element = find_element(browser, css)
  File "/kairos/tv/tv.py", line 444, in find_element
    element = WebDriverWait(browser, delay).until(
  File "/Library/Python/3.8/site-packages/selenium-3.141.0-py3.8.egg/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
```

It also breaks with the same error when trying to set `sell_fee` for instance which doesn't have the emoji in the label.

Anything else I can provide to help with debugging?

**Comment by timelyart** [comment]
Hmm - that is odd. I tested checkboxes, select boxes and normal input boxes. 

Did Kairos save a screenshot under your `<installation path>\Kairos\log` folder?

**Comment by marcfon** [comment]
> Did Kairos save a screenshot under your `<installation path>\Kairos\log` folder?

Yes, it did but there's nothing strange on that screenshot. Just the inputs tab open of the strategy.

What's even more strange is that changing the `initial_capital` value on the `properties tab` does work correctly.

**Comment by timelyart** [comment]
Is the field `_name` an input for ticker symbols?

**Comment by timelyart** [comment]
If it was.... then that is why it broke. Inputs for symbols weren't supported. 

I added support for it in [version v2.63](https://github.com/timelyart/Kairos/releases/tag/v2.63).
Please, let me know if this fixed it for you.

**Comment by marcfon** [comment]
Not yet but v2.63 does add one addition error message compared the v2.62 (see below).

I've also uploaded a [screenshot](https://imgur.com/a/ixjiHMd) of the DOM tree of the specific field. Could it be that things are somehow nested weirdly?

```
2021-11-14 07:44:42.081 ERROR tv - set_indicator_dialog_value: unable to set sell_fee to 0.25
Traceback (most recent call last):
  File "/kairos/tv/tv.py", line 4281, in set_indicator_dialog_value
    element = find_element(browser, css)
  File "/kairos/tv/tv.py", line 444, in find_element
    element = WebDriverWait(browser, delay).until(
  File "/Library/Python/3.8/site-packages/selenium-3.141.0-py3.8.egg/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-11-14 07:44:42.094 ERROR tv - set_indicator_dialog_value: css not found: #overlap-manager-root div[class^="content"] div[class^="cell-"]:nth-child(12) span
Traceback (most recent call last):
  File "/kairos/tv/tv.py", line 4281, in set_indicator_dialog_value
    element = find_element(browser, css)
  File "/kairos/tv/tv.py", line 444, in find_element
    element = WebDriverWait(browser, delay).until(
  File "/Library/Python/3.8/site-packages/selenium-3.141.0-py3.8.egg/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-11-14 07:44:42.094 ERROR tv - set_indicator_dialog_value: Message: 
Traceback (most recent call last):
  File "/kairos/tv/tv.py", line 4281, in set_indicator_dialog_value
    element = find_element(browser, css)
  File "/kairos/tv/tv.py", line 444, in find_element
    element = WebDriverWait(browser, delay).until(
  File "/Library/Python/3.8/site-packages/selenium-3.141.0-py3.8.egg/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Comment by timelyart** [comment]
Kairos breaks on the `Sell Fee` field. Which is odd since setting floats / integers have been working for years now and is something I did test yesterday. Are you sure this is the first error in the log?

It used to be that the only input types were floats, integers and select boxes; and so I suspect the datetime fields will also break.
Is that strategy publicly available? So, I can check out the DOM myself.

**Comment by marcfon** [comment]
It also breaks on the name field which is just a string so I don't think floats are the problem specifically.

The script is closed source but I can ping the creator.

**Comment by timelyart** [comment]
I don't need the source... I only need to be able to add it to a chart.

**Comment by marcfon** [comment]
> I don't need the source... I only need to be able to add it to a chart.

I understand. The script is invite only.

Would it help if I send you the entire log on level 10?

**Comment by marcfon** [comment]
Here's by the way what I seen in `browser.log`.

```
2021-11-14 11:27:34.954 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:27:34.942Z:Platform.GUI.Widgetbar.DetailsWidget:Mount was called on already mounted widget" 
2021-11-14 11:28:27.490 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:28:27.488Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id process_orders_on_close in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:28:27.491 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:28:27.489Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id close_entries_rule in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:28:27.491 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:28:27.490Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id run_mode in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:28:27.491 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:28:27.490Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id alert_message in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:28:27.492 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:28:27.490Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id alert_type in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:28:27.492 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:28:27.491Z:Platform.GUI.PropertyDialog.Indicators.StrategyPage:Can't obtain currency from strategy report" 
2021-11-14 11:28:45.362 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:28:45.356Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id process_orders_on_close in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:28:45.363 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:28:45.361Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id close_entries_rule in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:28:45.363 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:28:45.361Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id run_mode in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:28:45.364 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:28:45.361Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id alert_message in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:28:45.364 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:28:45.362Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id alert_type in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:28:45.365 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:28:45.362Z:Platform.GUI.PropertyDialog.Indicators.StrategyPage:Can't obtain currency from strategy report" 
2021-11-14 11:29:03.348 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:29:03.330Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id process_orders_on_close in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:29:03.352 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:29:03.347Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id close_entries_rule in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:29:03.352 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:29:03.347Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id run_mode in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:29:03.353 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:29:03.347Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id alert_message in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:29:03.354 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:29:03.348Z:Platform.GUI.PropertyDialog.Indicators.MetaInfo:Unknown strategy input internal id alert_type in StrategyScript$PUB;0c061fbf787b4a7c96562c4243f4353a@tv-scripting-101" 
2021-11-14 11:29:03.355 WARNING 	 https://www.tradingview.com/static/bundles/main_chart.a78174ec88d38c89b406.js 776:1964 "2021-11-14T10:29:03.348Z:Platform.GUI.PropertyDialog.Indicators.StrategyPage:Can't obtain currency from strategy report" 

```

**Comment by timelyart** [comment]
> > I don't need the source... I only need to be able to add it to a chart.
> 
> I understand. The script is invite only.
> 
> Would it help if I send you the entire log on level 10?

Don't think so. We know where the issue is. The problem is that I don't have the DOM in order to find out why it works for my strategies me but not for this one.

Is the strategy fully loaded when Kairos tries to set the inputs/properties?

**Comment by marcfon** [comment]
I've pinged the developer of the script to see if he can jump in here and provide some assistance.

I think the strategy is fully loaded. How can I know for sure?

**Comment by timelyart** [comment]
> I've pinged the developer of the script to see if he can jump in here and provide some assistance.
> 
> I think the strategy is fully loaded. How can I know for sure?

You will see dots behind the name if it is still loading, or a red exclamation mark when it is unable to load.

**Comment by marcfon** [comment]
> You will see dots behind the name if it is still loading, or a red exclamation mark when it is unable to load.

I just double checked. It's fully loaded. I'm out of options what to test.

**Comment by timelyart** [comment]
Well, I suppose you will need to track down the fault for me.

From the Developers panel (F12) in the browser search (CTRL+F) for `#overlap-manager-root div[class^="content"] div[class^="cell-"]:nth-child(12) span`. This is the CSS that failed for the `Sell Fee` field. The CSS should point to the element that can receive keyboard input, in this case 0.25. If no element was found, remove ` span` from the CSS and see if that does the trick.

**Comment by marcfon** [comment]
I think you mean `nth-child(**2**)` not `nth-child(**12**)`  right? With `nth-child(**2**)` I get 333 results in the source.

Could it be that the `input` field is nested one level deeper than intended? See [screenshot](https://imgur.com/a/CEE7MVd).

**Comment by timelyart** [comment]
> I think you mean `nth-child(**2**)` not `nth-child(**12**)` right? With `nth-child(**2**)` I get 333 results in the source.
> 
> Could it be that the `input` field is nested one level deeper than intended? See [screenshot](https://imgur.com/a/CEE7MVd).

It should be `nth-child(**12**)`. That is the CSS Kairos is using. I take it `#overlap-manager-root div[class^="content"] div[class^="cell-"]:nth-child(12)` is not found in the DOM?

**Comment by marcfon** [comment]
> It should be `nth-child(**12**)`. That is the CSS Kairos is using. I take it `#overlap-manager-root div[class^="content"] div[class^="cell-"]:nth-child(12)` is not found in the DOM?

`nth-child(**12**)` returns 0 results in the DOM. Any value above 2 comes up blank.

**Comment by lvinniel** [comment]
> I don't need the source... I only need to be able to add it to a chart.

Hi, timelyart!  I'm the author of this indicator we are discussing.  Feel free to send me a private message in TradingView and I'll grant you access to my script so that you can add it to your charts.  My TV username is: prosum_solutions

**Comment by timelyart** [comment]
~~@marcfon are you using a TradingView indicator or a strategy to backtest with?~~

Nevermind. I got access to the strategy.

**Comment by timelyart** [comment]
So, I had a first look. 

The issue is twofold:
- Non-ascii characters, i.e. the icons. 
- Variables that have a checkbox as well as a value. 

I might add support for both of them or I may add second way of defining inputs. In which case I'll ignore the variable names and I'll just go from left to right and from top to bottom filling in values. In that case your input will look something like this:

`inputs: {["v2.5.13-3C"], ["QFL Bot"], ["Single-pair"], [0.1, 0.25], [0.1, 0.25], ["Trading View Custom Signal: QFL v2.5"]}`

Either way, it's going to take some effort to build the necessary support so don't expect a fix this week.

**Comment by marcfon** [comment]
Thanks @timelyart for looking deeper into this. Much appreciated! And thanks @lvinniel for jumping in here.

Any clue why "sell fee" isn't working either? It has no non-ascii characters and/or checkbox.

**Comment by timelyart** [comment]
Kairos scans the dialogue first to find the default inputs and properties. At that point it already goes awry.

**Comment by timelyart** [comment]
Fixed with [release v2.64](https://github.com/timelyart/Kairos/releases/tag/v2.64).

Please let me know if the issue indeed has been resolved.

**Comment by marcfon** [comment]
> Please let me know if the issue indeed has been resolved.

Thanks for the update but I'm still running into an weird issue. I see that a input field is correctly set to the value I have defined in stratgies.yaml but then quickly set back to the default value.

Also the session doesn't close. It keeps the browser open (on the properties tab) after the final request and kairos doesn't exit.

I see one error in the log and it's this one:

```
2021-11-26 16:48:25.253 ERROR tv - get_indicator_dialog_elements: Message: 
Traceback (most recent call last):
  File "/kairos/tv/tv.py", line 4300, in get_indicator_dialog_elements
    value_cells = find_elements(row, 'input, span[role="button"], div[class^="text"] > span', delay=1)
  File "/kairos/tv/tv.py", line 483, in find_elements
    elements = WebDriverWait(browser, delay).until(
  File "/usr/local/lib/python3.8/site-packages/selenium-3.141.0-py3.8.egg/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-11-26 16:48:25.257 ERROR tv - get_indicator_dialog_values: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/kairos/tv/tv.py", line 3509, in get_indicator_dialog_values
    result[title] = get_dialog_input_value(value_cells)
  File "/kairos/tv/tv.py", line 3482, in get_dialog_input_value
    for element in elements:
TypeError: 'NoneType' object is not iterable
```

**Comment by timelyart** [comment]
Could you please share your YAML (excluding any private data)?

**Comment by marcfon** [comment]
Of course. I've kept it as simple as possible for the test.

```
charts:
- url: https://www.tradingview.com/chart/XXXX/
  timeframes: [1 hour]
  watchlists: [kairos]
  strategies:
  - name: "QFL3C"
    pane_index: 0
    inputs: {'name': {0: 'Kairos is here', 1: 'Single-pair'}}
    properties: {}
webdriver:
  run-in-background: no
```

**Comment by timelyart** [comment]
Thank you. Select boxes are indeed bugged.

**Comment by timelyart** [comment]
Apparently, the select boxes were fine but the color picker fields did not work. 

As of [release v2.66](https://github.com/timelyart/Kairos/releases/tag/v2.66) they will be ignored as their scope is limited anyway within the context of automated testing.

Please, let me know if Kairos is purring as nicely as on my machine.

**Comment by marcfon** [comment]
> Please, let me know if Kairos is purring as nicely as on my machine.

Initial test looking good over here!  Will do more extensive tests soon.

Just a quick check. Should there be values in the `summary (total / interval / symbol) ` section of the output file? Right now all those values are 0. The `raw` section does provide correct values from the backtest.

**Comment by timelyart** [comment]
Yes, there should be. You may see a bunch of 0s for `symbols` if you have only defined a single timeframe, or 0s if you have one symbol on one timeframe. You might want to run in the foreground with a subset of markets first. I noticed that the strategy sometimes doesn't return results but empty results should be discarded.

**Comment by marcfon** [comment]
Okay, I'm now running just with a single pair on a single timeframe so that might explain the 0s.

Something else strange is going on...

Can you test on your end what happens when you test this input options:`'take_profit_(%)': [2, 5]`

I see on the foreground that the input field is updated with the values but the strategy isn't updated accordingly. It almost looks like the cancel button is clicked rather than ok.

What makes it even more strange is that I don'r have the issue when I run these input options: `'bars_on_left': {0: 2, 1: 'yes', 2: [2, 4]}`

**Update**
Same problem emerges for `safety_order_step_scale` for instance. I've noticed that take_profit_(%) and safety_order_step_scale aren't returned in the list of default inputs. Could it be related to that?

**Comment by timelyart** [comment]
How goes that song again ... "100 bugs in the code, fix one, commit..... 101 bugs in the code". Accidentally introduced a new bug. 

It should be good as of [release v2.67](https://github.com/timelyart/Kairos/releases/tag/v2.67) (hopefully). 
Do let me know how it goes.

**Comment by marcfon** [comment]
> Do let me know how it goes.

Progress but not quite there yet. `safety_order_step_scale` and `take_profit_(%)` are back in the default inputs list. And I can see that the fields are being updated in the strategy.

But the problem where it looks like ok button isn't pressed still is there. As in the set values don't impact the output strategy.

While something like `{'bars_on_left': {0: 2, 1: 'yes', 2: 4}}` does work correctly.

**Comment by timelyart** [comment]
This should work as intended. I am at least getting different results per set of inputs. At least as of [release v2.68](https://github.com/timelyart/Kairos/releases/tag/v2.68).

**Comment by marcfon** [comment]
Unfortunately still the same issue on my end. Using this `inputs: {'bars_on_left': {0: 2, 1: 'yes', 2: [2, 4]}}` does return the different net profit values in the output but using this `inputs: {'safety_order_step_scale': [1, 2]}` doesn't. 

Could it be a delay thing? As in too short between changing the input value and clicking the okay button? I haven't changed the default delays as specified in kairos.cfg.

**Comment by timelyart** [comment]
I just tested `inputs: {'safety_order_step_scale': [1, 2]}` and it works fine to me.

However, `safety_order_step_scale: 2` never yields results, and when I set `safety_order_step_scale` manually to 2; it always returns an error for me. Could that be the issue?

**Comment by marcfon** [comment]
> I just tested `inputs: {'safety_order_step_scale': [1, 2]}` and it works fine to me.

Any clue where to look next? The strange thing is that I see the values being changed on the `safety_order_step_scale` values being changed on the foreground. 

> However, `safety_order_step_scale: 2` never yields results, and when I set `safety_order_step_scale` manually to 2; it always returns an error for me. Could that be the issue?

The only thing I can think of is that you might be getting an error because your backtest period is too short and there are no trades in that period.

**Comment by timelyart** [comment]
I used the default values on multiple time frames of a market that has been around for 5 years. So, I don't know...

The only thing I can think of, is that the chart (and therefore the data) isn't loaded quickly enough on the background but that doesn't make sense since other settings do work for you. 

Which OS, chrome and webdriver version are you using?

**Comment by marcfon** [comment]
> The only thing I can think of, is that the chart (and therefore the data) isn't loaded quickly enough on the background but that doesn't make sense since other settings do work for you.

I'm curious if it's just the single field input elements that have problems? The `bars_on_left` is a multi field element.

> Which OS, chrome and webdriver version are you using?

```
2021-12-08 14:44:17.097 INFO tv - run: Running on a darwin operating system
2021-12-08 14:44:19.803 INFO tv - check_driver: browser version: 96.0.4664.55
2021-12-08 14:44:19.803 INFO tv - check_driver: driver version: 95.0.4638.69
```

**Update**
Just tested with `inputs: {'base_order_size': {0: "Base", 1: "50"}}` as another multi field input and this works as expected.

**Comment by marcfon** [comment]
Could it be that the input single field is still "active" after it's value has changed? As in maybe you need to switch out of the field before the new input value gets "committed" to the strategy. Just purely guessing here.

**Comment by timelyart** [comment]
Well, you can try to get the [up-to-date web driver](https://chromedriver.storage.googleapis.com/index.html?path=96.0.4664.45/) for your browser.

It is possible that the field doesn't register the change until it loses focus. You can try to test if that is the case by defining additional input fields, e.g. `inputs: {'safety_order_step_scale': [1, 2], take_profit_(%): 4}`
I would be surprised if that was the case though, since Kairos sends a mouse click to press the `submit` button.

It could be how MacOs + chromium works. Unfortunately, I won't be able to test/fix that as I don't own a MacOs machine.

**Comment by marcfon** [comment]
So I tried this `inputs: {'name': {0: "Kairos", 1: "Single-pair"}}` as a test and things gets even weirder... The name is updated in the field and a brief moment later it's reverted to the back default input value. Could be totally unrelated but if something similar is happening with the other fields it could explain why the values aren't changing. If somehow the default value is put back into the input field before the submit button is pressed.

Also `inputs: {'take_profit_(%)': 2, 'name': {0: "Kairos", 1: "Single-pair"}}` didn't have the desired effect. So we can probably eliminate changing focus.

Just to be sure I've updated the driver but didn't make a difference.

**Comment by timelyart** [comment]
I tested it on a Linux machine and I got errors when trying to set integer values. It's fixed in [release v2.69](https://github.com/timelyart/Kairos/releases/tag/v2.69). 

I didn't encounter any other errors on Linux. So, if this release doesn't fix it for you then I would be at a loss on how to proceed further.

**Comment by marcfon** [comment]
Still no luck. I've sent you a few screen recordings via mail with the log output in situations where it works and when it doesn't. Maybe that will help to solve this mystery.

**Comment by timelyart** [comment]
I did find a bug that specifically affected MacOS users. Can you try [release v2.70](https://github.com/timelyart/Kairos/releases/tag/v2.70)?

**Comment by marcfon** [comment]
> I did find a bug that specifically affected MacOS users. Can you try [release v2.70](https://github.com/timelyart/Kairos/releases/tag/v2.70)?

I think you've nailed it! Did a bunch of tests today and everything seems to be working as expected.

Thank you for not giving up on this one :)

**Comment by timelyart** [comment]
Happy it is finally working for you. 👍
