### ISSUE TITLE
Setting date field in backtest fails

### ISSUE THREAD

**Issue by marcfon** [timelyart/Kairos#45]
Setting a date field using an input like this `inputs: {'start_date/time': {0: '2021-02-06', 1: '01:00'}, 'stop_date/time': {0: '2021-05-01', 1: '00:00'}}` fails with the following error:

```
2021-12-09 20:21:20.058 ERROR tv - set_indicator_dialog_element: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=96.0.4664.93)
Traceback (most recent call last):
  File "/kairos/tv/tv.py", line 4377, in set_indicator_dialog_element
    clear(element)
  File "/kairos/tv/tv.py", line 2452, in clear
    element.send_keys(SELECT_ALL)
  File "/Library/Python/3.8/site-packages/selenium-3.141.0-py3.8.egg/selenium/webdriver/remote/webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "/Library/Python/3.8/site-packages/selenium-3.141.0-py3.8.egg/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/3.8/site-packages/selenium-3.141.0-py3.8.egg/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/3.8/site-packages/selenium-3.141.0-py3.8.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=96.0.4664.93)
```

I think this could be because the date field opens up a date selection dialogue which interferes with the input.

**Comment by timelyart** [comment]
A `StaleElementReferenceException` is thrown when an element has been called to by Kairos to be updated but has already been updated by the server.

**Comment by timelyart** [comment]
I added a retry mechanism for when a StaleElementReferenceException occurs in [release v2.70](https://github.com/timelyart/Kairos/releases/tag/v2.70). This should fix it.

There is one more thing though, when setting the date TV sets it automatically to one day before. Very odd behavior.

**Comment by marcfon** [comment]
> I added a retry mechanism for when a StaleElementReferenceException occurs in [release v2.70](https://github.com/timelyart/Kairos/releases/tag/v2.70). This should fix it.

Confirmed! Dates work as expected in 2.70. Consider this one closed.

> There is one more thing though, when setting the date TV sets it automatically to one day before. Very odd behavior.

Yeah I noticed that too.
