### ISSUE TITLE
Ignore invalid markets when backtesting

### ISSUE THREAD

**Issue by timelyart** [timelyart/Kairos#52]
**Describe the bug**
When backtesting a market that is no longer listed will result in unrecoverable `Timeout waiting for has_gone_stale` errors. 

**To Reproduce**
1. Make a watchlist with at least one market that is no longer listed (or never existed)
2. Backtest a strategy with the watchlist from point 1.
3. See error
```
2021-12-20 14:41:18.061 ERROR tv - get_strategy_statistic: Timeout waiting for has_gone_stale
Traceback (most recent call last):
  File "/kairos272/tv/tv.py", line 4226, in get_strategy_statistic
    wait_for_element_is_stale(previous_elements[key])
  File "/kairos272/kairos/tools.py", line 319, in wait_for_element_is_stale
    wait_for(has_gone_stale)
  File "/kairos272/kairos/tools.py", line 294, in wait_for
    raise Exception(
Exception: Timeout waiting for has_gone_stale
```

**Expected behavior**
No errors should happen. The market should simply be ignored.

**Additional context**
See issue #46.

**Comment by timelyart** [comment]
Solved in [release v2.75](https://github.com/timelyart/Kairos/releases/tag/v2.75).
